version: '3'

networks:
  glowing-train:
    name: glowing-train
    driver: bridge

services:
  database:
    container_name: glowing-train
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=movies_library
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 14562:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - glowing-train
